# Build settings
markdown: kramdown
highlighter: rouge

# Site settings
title: "Fit and Fueled"
subtitle: "Personal Training & Nutritional Therapy"

meta:
  title: "Fit and Fueled - Personal Training & Nutritional Therapy - Austin, TX"
  description: "Meryl Carey is a certified personal trainer in Austin, TX. Contact me to take your fitness to the next level."
  keywords: "personal training personal-training nutritional therapy nutritional-therapy nutrition austin texas fitness health"

# logo_text: "M"

email: meryl@merylcarey.com
#blog logo
# logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/dumbbells.JPG"

name: 'Fit and Fueled'
author: 'Meryl Carey'
# author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://www.merylcarey.com" # the base hostname & protocol for your site
baseurl: ""

fb_app_id: 1714869315409187
# social icons and sharing options
social:
  - icon:	instagram
    url:	https://instagram.com/merylcarey
    desc: Follow me on Instagram

  - icon:	facebook
    url:	https://facebook.com/mcfitaustin
    desc: Connect with me on facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  # - icon:	twitter
    # url:	https://twitter.com/dirkfabisch
    # desc: Follow me on twitter
    # share_url: http://twitter.com/share
    # share_title: ?text=
    # share_link: "&amp;url="

  # - icon:	github
    # url:	https://github.com/dirkfabisch
    # desc:	Fork me on github
    # share_url:
    # share_title:
    # share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
